visualize: True
visual_scale: 15
lidar_reversed: False
orthogonal_boxes: True
front_lidar_x: 0.0
front_lidar_y: 0.0
front_lidar_z: 1.37
front_lidar_x_angle: -6.0
front_lidar_y_angle: 0.0
front_lidar_z_angle: 0.0
rear_lidar_x: -0.05
rear_lidar_y: -5.45
rear_lidar_z: 0.75
rear_lidar_x_angle: 0.0
rear_lidar_y_angle: 0.0
rear_lidar_z_angle: 0.0
filter_leaf_size: 0.058
segmentation_threshold: 0.3
cluster_tolerance: 0.5
min_cluster_size: 5
max_cluster_size: 20000
rear_filter_leaf_size: 0.18
rear_segmentation_threshold: 0.3
rear_cluster_tolerance: 0.5
rear_min_cluster_size: 3
rear_max_cluster_size: 20000
file_record: False
file_record_frameinterval: 5
vehicle_corner1_x: -1.1
vehicle_corner1_y: 0.55
vehicle_corner2_x: 0.9
vehicle_corner2_y: 0.55
vehicle_corner3_x: -1.05
vehicle_corner3_y: 5.55
vehicle_corner4_x: 1.05
vehicle_corner4_y: 5.55
min_hmax: 0.6
max_hmin: 0.6
max_hmax: 3.5
min_axis_distance: -20.0
max_distance: 20.0
gps_shift_x: 0.0
gps_shift_y: 0.0
gps_shift_y_back: -3.1
zed_x: -0.12
zed_y: 0.93
zed_z: -2.0
projection_size: 2300
visualize_projection: True
area_to_accept: 0.7
area_part: 0.3
