pointcloud_to_laserscan:
  ros__parameters:
    min_height: 0.1
    max_height: 0.3
    angle_min: -3.141
    angle_max: 3.141
    angle_increment: 0.00153
    queue_size: 100
    scan_time: 0.1
    range_min: 0.01
    range_max: 100.0
    target_frame: 'base_link'
    transform_tolerance: 0.0
    use_inf: true