states_dir: "robocross/"
states:
  start: "StartState.py"
  moving: "MovingState.py"
  astarmoving: "AStarMovingState.py"
  gpsfollow: "GPSFollowState.py"
  lanefollow: "LaneFollowState.py"
  paused: "PausedState.py"
  stopped: "StoppedState.py"
  emergency: "EmergencyState.py"
  turn: "TurnState.py"
workers:
  lightswitch: "LightSwitchDetectorWorker.py"
  roadsign: "RoadSignDetectorWorker.py"
  ipm: "IPMWorker.py"
  semanticsegmentation: "SemanticSegmentationWorker.py"
  lanelinedetection: "LaneLineDetectionWorker.py"
  pathplanning: "PathPlanningWorker.py"
  behavioranalysis: "BehavioralAnalysisWorker.py"
  reedsshepp: "ReedsSheppPlanningWorker.py"
  roadmarkingdetection: "RoadMarkingDetectionWorker.py"
workerstates:
  start: ["semanticsegmentation", "ipm", "lanelinedetection", "roadsign", "roadmarkingdetection"]
  moving: ["semanticsegmentation", "ipm", "lanelinedetection", "lightswitch", "roadsign", "roadmarkingdetection", "behavioranalysis"] # "pathplanning"
  astarmoving: ["semanticsegmentation", "ipm", "lanelinedetection", "lightswitch", "roadsign", "roadmarkingdetection", "behavioranalysis", "pathplanning"]
  # astarmoving: ["semanticsegmentation", "ipm", "lanelinedetection", "lightswitch", "roadsign", "roadmarkingdetection", "behavioranalysis", "pathplanning"]
  lanefollow: ["semanticsegmentation", "ipm", "lanelinedetection", "lightswitch", "roadsign", "roadmarkingdetection", "behavioranalysis", "pathplanning"]
  gpsfollow: ["semanticsegmentation", "ipm", "lanelinedetection", "lightswitch", "roadsign", "roadmarkingdetection", "behavioranalysis"] #, "pathplanning"]
  stopped: ["semanticsegmentation", "ipm", "lanelinedetection", "roadsign", "roadmarkingdetection"]
  paused: ["semanticsegmentation", "ipm", "lanelinedetection", "roadsign", "roadmarkingdetection"]
  turn: ["semanticsegmentation", "ipm", "lanelinedetection", "roadmarkingdetection", "reedsshepp"]
  emergency: []
transitions:
  start:
    start_move: ["astarmoving"] # "gpsfollow"
    stop: ["stopped"]
    pause: ["paused"]
  gpsfollow:
    start_astar: ["astarmoving"]
    start_move: ["moving"]
    # start_gps_follow: ["gpsfollow"] 
    # start_lane_follow: ["lanefollow"]
    pause: ["paused"]
    stop: ["stopped", "emergency"]
    turn: ["turn"]
  astarmoving:
    start_gps_follow: ["gpsfollow"]
    pause: ["paused"]
    stop: ["stopped", "emergency"]
    turn: ["turn"]
  moving:
    start_gps_follow: ["gpsfollow"]
    start_lane_follow: ["lanefollow"]
    stop: ["stopped", "emergency"]
    turn: ["turn"]
  lanefollow:
    start_gps_follow: ["gpsfollow"] 
    start_move: ["moving"]
    stop: ["stopped", "emergency"]
    turn: ["turn"]
  paused:
    start_move: ["gpsfollow"]
  stopped:
    start_move: ["gpsfollow"]
  emergency:
    reset: ["start"]
  turn:
    start_move: ["moving"]
    stop: ["stopped", "emergency"]
map-elements:
  - element:
    id: "start"
    name: !!str Точка старта
    ol-type: !!str Point
    color: !!str 00ff00
  - element:
    id: "turn"
    name: !!str Зона разворота
    ol-type: !!str Polygon
    color: !!str ffff00
  - element:
    id: "finish"
    name: !!str Зона  финиша
    ol-type: !!str Polygon
    color: !!str ff0000
  - element:
    id: "nolanes"
    name: !!str Зона движения без линий разметки 
    ol-type: !!str Polygon
    color: !!str 0000ff
  - element:
    id: "moving"
    name: !!str Путь следования
    ol-type: !!str LineString
    color: !!str 0000ff
  - element:
    id: "moving_back"
    name: !!str Путь следования задом
    ol-type: !!str LineString
    color: !!str 00ff00
  - element:
    id: "terminal"
    name: !!str Зона терминала
    ol-type: !!str Polygon
    color: !!str ffa500
  - element:
    id: "traffic_light"
    name: !!str Зона светофора
    ol-type: !!str Polygon
    color: !!str 000000
  - element:
    id: "crosswalk"
    name: !!str Зона пешеходного перехода
    ol-type: !!str Polygon
    color: !!str ffffff
  - element:
    id: "stop"
    name: !!str Зона остановки
    ol-type: !!str Polygon
    color: !!str 800080
  - element:
    id: "speed7"
    name: !!str Зона скорости 7
    ol-type: !!str Polygon
    color: !!str fe00f0
  - element:
    id: "speed20"
    name: !!str Зона скорости 20
    ol-type: !!str Polygon
    color: !!str fefcba
  - element:
    id: "speed30"
    name: !!str Зона скорости 30
    ol-type: !!str Polygon
    color: !!str aef0b0
  - element:
    id: "speed40"
    name: !!str Зона скорости 40
    ol-type: !!str Polygon
    color: !!str fe00cf
  - element:
    id: "obstacle_stop"
    name: !!str Зона остановки перед препядствием
    ol-type: !!str Polygon
    color: !!str 804030
  - element:
    id: "next_segment"
    name: !!str Зона следующего сегмента
    ol-type: !!str Polygon
    color: !!str ff00ff
  - element:
    id: "to_gpsfollow"
    name: !!str Зона пеерхода следования по GPS
    ol-type: !!str Polygon
    color: !!str 40a8f7
  - element:
    id: "to_obstacles"
    name: !!str Зона пеерхода на объезд пряпядствий 
    ol-type: !!str Polygon
    color: !!str 83eb34
  - element:
    id: "pause_tick_50"
    name: !!str Зона паузы на 50 тиков 
    ol-type: !!str Polygon
    color: !!str 40524e